# -*- coding: utf-8 -*-
"""conditional statements

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DKJVx_NhN0UlQXrOXRvN5VTaCmAz04gs
"""

num = int(input("enter number"))
if num<0:
  print("negative")
elif num>0:
  print("positive")
else:
  print("neutral")

# <
# >
# <=
# >=
# ==
# !=

num = int(input("enter number"))
if num%2==0:
  print("even")
else:
  print("odd")

"""{

}
"""

num1 = int(input("enter first num1: "))
num2 = int(input("enter first num2: "))
num3 = int(input("enter first num3: "))

if num1>num2:
  if num1 > num3:
    print("num1 is the greatest ")
  else:
    print("num3 is the greatest")
elif num2>num1:
  if num2 > num3:
    print("num2 is the greatest ")
  else:
    print("num3 is the greatest")
else:
  print("all are equal")