# -*- coding: utf-8 -*-
"""World Population.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tQUksve6-DgbaCPMKNi18VxreKhnCG_V
"""

import numpy as np

import pandas as pd

df=pd.read_csv("/world_population.csv")
df

df.head()

df.shape

df.info()

df.isnull().sum()

continent_df=df.groupby(by='Continent').sum()
continent_df

import matplotlib.pyplot as plt
import seaborn as sbn

continent_df['2022 Population'].plot(kind="pie",figsize=(10,5),shadow=True,autopct="%1.1f%%")
plt.title('Population by continent')
plt.axis('equal')
plt.show()

asian_countries = df.loc[df["Continent"]=="Asia"].sort_values(by=["2022 Population"], ascending=False, ignore_index=True)


african_countries = df.loc[df["Continent"]=="Africa"].sort_values(by=["2022 Population"], ascending=False, ignore_index=True)


european_countries = df.loc[df["Continent"]=="Europe"].sort_values(by=["2022 Population"], ascending=False, ignore_index=True)


na_countries = df.loc[df["Continent"]=="North America"].sort_values(by=["2022 Population"], ascending=False, ignore_index=True)


oc_countries = df.loc[df["Continent"]=="Oceania"].sort_values(by=["2022 Population"], ascending=False, ignore_index=True)

sa_countries = df.loc[df["Continent"]=="South America"].sort_values(by=["2022 Population"], ascending=False, ignore_index=True)

top_5_countries = asian_countries[["Country/Territory", "2022 Population"]].sort_values(by="2022 Population", ascending=False).head(5)

sbn.barplot(data=top_5_countries, x="Country/Territory", y="2022 Population")
plt.xlabel("Country/Territory")
plt.ylabel("2022 Population")
plt.title("Top 5 Countries by Population in Asian Countries")

plt.show()

top_5_african = african_countries[["Country/Territory", "2022 Population"]].sort_values(by="2022 Population", ascending=False).head(5)

sbn.barplot(data=top_5_african, x="Country/Territory", y="2022 Population")
plt.xlabel("Country/Territory")
plt.ylabel("2022 Population")
plt.title("Top 5 Countries by Population in African Countries")

top_5_european =european_countries [["Country/Territory", "2022 Population"]].sort_values(by="2022 Population", ascending=False).head(5)

sbn.barplot(data=top_5_european, x="Country/Territory", y="2022 Population")
plt.xlabel("Country/Territory")
plt.ylabel("2022 Population")
plt.title("Top 5 Countries by Population in europ Countries")

top_5_na =na_countries [["Country/Territory", "2022 Population"]].sort_values(by="2022 Population", ascending=False).head(5)

sbn.barplot(data=top_5_na, x="Country/Territory", y="2022 Population")
plt.xlabel("Country/Territory")
plt.ylabel("2022 Population")
plt.title("Top 5 Countries by Population in North America Countries")

top_5_oc =oc_countries [["Country/Territory", "2022 Population"]].sort_values(by="2022 Population", ascending=False).head(5)

sbn.barplot(data=top_5_oc, x="Country/Territory", y="2022 Population")
plt.xlabel("Country/Territory")
plt.ylabel("2022 Population")
plt.title("Top 5 Countries by Population in Ocien Countries")

top_5_sa =sa_countries [["Country/Territory", "2022 Population"]].sort_values(by="2022 Population", ascending=False).head(5)

sbn.barplot(data=top_5_sa, x="Country/Territory", y="2022 Population")
plt.xlabel("Country/Territory")
plt.ylabel("2022 Population")
plt.title("Top 5 Countries by Population in South America Countries")

plt.subplots(figsize=(10,5))
trend = df.iloc[:,5:13].sum().sort_values(ascending=True)

sbn.lineplot(x=trend.index, y=trend.values, marker="o")
plt.xticks(rotation=20)
plt.ylabel("Population")
plt.title("World Population Trend (1970-2022)")
plt.show()